### PR TITLE
 commiting changes for pre_existing Auth server resources

### PR DESCRIPTION
**Pull request by patluri43**
Added support for pre_existing authz server resources.

If claim already exists, set "pre_existing"  flag to true to update the claim
id autzpolicy already exists, set "pre_existing" flag to true to update the policy

### CODE REVIEW

**Review by quantumew — COMMENTED** [review]
If I understand this change correctly, this wouldn't be supported functionality in the provider. You would instead need to import the existing resource, then run your plan, and apply. 

```
terraform import okta_auth_server.my_test <id from okta>
```

With that said once I find an open weekend I am planning on writing a tool that will help with this process. Feel free to follow this https://github.com/quantumew/terraforming-okta for updates. It will essentially aid people in the brownfield state wanting to use Terraform with Okta.

**Comment by patluri43** [comment]
Thank you, we have a usecase where we are planning to modify preexiting claims/policy in 100's of okta tenant's and we are trying to avoid manual import steps.

**Comment by quantumew** [comment]
@patluri43 I can understand that sentiment, it can be quite tedious. Unfortunately that is [the way Terraform works](https://www.terraform.io/docs/import/index.html). It requires you to import existing resources. I am not sure what your timeline is but I would recommend waiting for the aforementioned tool we are planning on building (open to contributions!), or script it. 

Here is the basic plan: https://github.com/quantumew/terraforming-okta/issues/1#issuecomment-534509371

**Comment by ocxo** [comment]
Thanks for the contribution @patluri43! This repo has officially moved to Hashicorp's collection of Terraform Providers at https://github.com/terraform-providers/terraform-provider-okta/. If you still wish to see this PR land on the provider, please re-open at https://github.com/terraform-providers/terraform-provider-okta/pulls.

**Pull request closed without merging**
