### PR TITLE
Update import path everywhere in preparation for move

### PR DESCRIPTION
**Pull request by quantumew**
See #269

### CODE REVIEW

**Comment by cgriggs01** [comment]
👍

**Comment by quantumew** [comment]
Screen Shot 2019-10-15 at 5 32 03 PM

**Comment by quantumew** [comment]
@cgriggs01 Let me know when to merge this. Due to the magic of Go modules this works but I updated all of the instructions to point to the new repo so just want to wait to merge. I also found some other Articulate specific stuff in the docs I tore out. Should be good to go now.

**Comment by ocxo** [comment]
Thanks for the contribution @quantumew! This repo has officially moved to Hashicorp's collection of Terraform Providers at https://github.com/terraform-providers/terraform-provider-okta/. If you still wish to see this PR land on the provider, please re-open at https://github.com/terraform-providers/terraform-provider-okta/pulls.

**Pull request closed without merging**
