### PR TITLE
expose external_name to user profile

### PR DESCRIPTION
**Pull request by jlew**
The external name of the user profile was not exposed.

This pr exposes this field.  I don't quite understand the base vs subschema so this may also need to be added in the base, but this fix meets our needs.

### CODE REVIEW

**Comment by jlew** [comment]
Probably another non-documented field:

Screenshot from Profile Editor:
image

Once it is created it is readonly.

UI for creating the attribute on the application profile:
image

The JSON
```JSON
{
   "title":"solutionId",
   "type":"string",
    "externalName":"solutionId",
   "mutability":"READ_WRITE",
   "scope":"NONE",
   "validationType":"HARD"
}
```

**Comment by quantumew** [comment]
@jlew Thanks for the info. Undocumented, property nooooo 😄. I think we can remove the `ForceNew` unless I am missing something, then we can merge this. I will get an acceptance test added for this in the future. Need to figure out what feature it is tied to, I don't see it in my account.

**Comment by jlew** [comment]
The UI doesn't let us change that field after created, so i am assuming the backend will enforce new as well.

**Comment by jlew** [comment]
This is the app profile of the user.

So create an idp, then once you create the idp you should be able to add new profile attributes to that idp.


```HCL
resource okta_app_user_schema solutionId {
  index       = "solutionId"
  master      = "PROFILE_MASTER"
  permissions = "READ_ONLY"
  title       = "solutionId"
  type        = "string"
  app_id      = okta_idp_oidc.solution-idpeach.key.id
  required    = false
  external_name = "solutionId"
}
```

**Pull request merged**
